(:assets ("map" "alien")
 :world ((:width 14
          :height 23
          :tile-size (64 64)
          :tile-shape :hexagon
          :tiles #2a((:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)
                     (:hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex :hex)))))
