(in-package :tradewarz)

(defun key-down (key state mod-key scancode unicode)
  (declare (ignore state mod-key scancode unicode))
  (case key
    (:sdl-key-a (gl:disable :blend))
    (:sdl-key-s (gl:enable :blend))
    (:sdl-key-d (gl:blend-func :src-alpha :one-minus-src-alpha))
    (:sdl-key-f (gl:blend-func :one :one))
    (:sdl-key-1 (gl:tex-parameter :texture-2d :texture-min-filter :linear-mipmap-linear))
    (:sdl-key-2 (gl:tex-parameter :texture-2d :texture-min-filter :linear-mipmap-nearest))
    (:sdl-key-3 (gl:tex-parameter :texture-2d :texture-min-filter :linear))
    (:sdl-key-4 (gl:tex-parameter :texture-2d :texture-min-filter :nearest))
    (:sdl-key-5 (gl:tex-parameter :texture-2d :texture-mag-filter :linear))
    (:sdl-key-6 (gl:tex-parameter :texture-2d :texture-mag-filter :nearest))
    (:sdl-key-escape (sdl:push-quit-event))
    )
  )
